const CHECK_INT = 0;
const CHECK_INT_FORMAT = 1;
const CHECK_DATE_FORMAT = 2;
const CHECK_TIME_FORMAT = 3;
const ZERO_INT_ALLOWED = 101;

module.exports = {
    CHECK_INT, CHECK_INT_FORMAT, CHECK_DATE_FORMAT, CHECK_TIME_FORMAT, ZERO_INT_ALLOWED
}